export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_BY_TYPE = "FILTER_BY_TYPE";
export const FILTER_BY_COLOR = "FILTER_BY_COLOR";
export const FILTER_BY_SIZE = "FILTER_BY_SIZE";

export const SORT_BY_PRICE = "SORT_BY_PRICE";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

export const CREATE_ORDER = "CREATE_ORDER";
export const CLEAR_ORDERS = "CLEAR_ORDER";
export const FETCH_ORDERS = "FETCH_ORDERS";

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const SHOW_DETAIL_REQUEST = "SHOW_DETAIL_REQUEST";
export const SHOW_DETAIL_SUCCESS = "SHOW_DETAIL_SUCCESS";
export const SHOW_DETAIL_FAIL = "SHOW_DETAIL_FAIL";
