export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_TYPE = "FILTER_PRODUCTS_BY_TYPE";
export const FILTER_PRODUCTS_BY_COLOR = "FILTER_PRODUCTS_BY_COLOR";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";

export const SORT_PRODUCTS_BY_PRICE = "SORT_PRODUCTS_BY_PRICE";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

export const CREATE_ORDER = "CREATE_ORDER";
export const CLEAR_ORDERS = "CLEAR_ORDER";
export const FETCH_ORDERS = "FETCH_ORDERS";
